apiVersion: apps/v1
kind: Deployment
metadata:
  name: personas-api
  namespace: jfaa-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personas-api
  template:
    metadata:
      labels:
        app: personas-api
    spec:
      containers:
      - name: personas-api
        image: localhost:5000/personas-api:2
        env:
          - name: ConnectionString__DefaultConnection
            valueFrom:
              secretKeyRef:
                name: personas-api-secrets
                key: connection-string
        ports:
        - containerPort: 8080