apiVersion: apps/v1
kind: Deployment
metadata:
  name: Proyect-Soap
  namespace: Proyect-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personas-api
  template:
    metadata:
      labels:
        app: personas-api
    spec:
      containers:
      - name: personas-api
        image: localhost:4000/personas-api:1
        env:
          - name: ConnectionStrings__DefaultConnection
            valueFrom:
              secretKeyRef:
                name: personas-api-secrets
                key: connection-string
        ports:
        - containerPort: 8080