apiVersion: v1
kind: Service
metadata:
  name: personas-api-svc
  namespace: Proyect-backend
spec:
  selector:
    app: personas-api
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP