apiVersion: v1
kind: Service
metadata:
  name: my-mongodb
  namespace: bagm-databases
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb
  type: ClusterIP
