apiversion: apps/v1
kind: Delpoyment
metadata: 
  name: users-api
  namespace: JFAA-api
spec:
  replicas: 1 
  selector: 
    matchLabels: 
      app: users-api
  template: 
    metadata: 
      labels: 
        app: users-api
    spec:
      containers:
        - name: users-api
          image: localhost:5000/users-api:1
          env:
          - name: "UserServiceEndpoint"
            value: "http://users-api-svc.JFAA-api.svc-cluster.local:8080"
          - name: "Authentication__Authority"
            value: "http://public.hydra.test"
          - name: "Authentication__Issuer"
            value: "http://public.hydra.test/"
          - name: "PostgreSql__Host"
            value: "postgres-svc.JFAA-api.svc.cluster.local"
          - name: "Postgre__Port"
            value: "5432"
          - name: "PostgreSql__Database"
            valueFrom:
              secretKeyRef: 
                name: users-api-secrets
                key: database-name
          - name: "PostgreSql__Username"
            valueFrom:
              secretKeyRef:
                name: users-api-secrets
                key: username
          - name: "PostgreSql__Password"
            valueFrom: 
              secretKeyRef:
                name: users-api-secrets
                key: password
          ports:
            - containerPort: 8083