version: '3.8'

services:
  restapi:
    build: .
    container_name: restapi
    ports:
      - "8080:4000"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - appnetwork

  db:
    image: postgres:latest
    container_name: postgresdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: restapidb
    ports:
      - "5432:5432"
    networks:
      - appnetwork
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - appnetwork

networks:
  appnetwork:
    driver: bridge
