version: "3.9"

services:
  RestAPI:
    container_name: RestAPI
    image: inventory:1
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://user:password@RestAPI_db:5432/postgres
    restart: always
    depends_on:
    - RestAPI_db
    - RestAPI_cache
    networks:
      - mynetwork
  
  RestAPI_db:
    container_name: RestAPI_db
    image: postgres:latest
    ports:
      - "5432:5432"  
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=postgres 
    volumes:
        - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

  RestAPI_cache:
    image: redis:latest
    container_name: RestAPI_cache
    ports:
     - "6379:6379"
    networks:
      - mynetwork

volumes:
  pgdata: {}

networks:
  mynetwork:
    driver: bridge