apiVersion: v1
kind: Service
metadata: 
  name: users-api-svc
  namespace: JFAA-api
spec:
  type: LoadBalancer
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: users-api