apiVersion: v1
kind: Service
metadata:
  name: restapi
  namespace: jfaa-api
  labels:
    app: restapi
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: restapi
  type: LoadBalancer
