apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi-db
  namespace: bagm-databases
  labels:
    app: restapi-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restapi-db
  template:
    metadata:
      labels:
        app: restapi-db
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_USER
          value: "user"
        - name: POSTGRES_DB
          value: "postgres"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
