apiVersion: v1
kind: Service
metadata:
  name: restapi-db
  namespace: bagm-databases
  labels:
    app: restapi-db
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: restapi-db
  clusterIP: None
